info:
  id: ${spring.application.name}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring:
  jpa:
    generate-ddl: true
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true
  zipkin:
    host: localhost
    base-url: http://localhost:9411

#logging:
#  level:
#    org:
#      springframework:
#        security: INFO
#        web: INFO
#    com:
#      netflix:
#        eureka: 'OFF'
#        discovery: 'OFF'

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000

#eureka:
#  instance:
#    hostname: localhost
#    nonSecurePort: 8080
#    prefer-ip-address: true
#    leaseRenewalIntervalInSeconds: 5
#  client:
#    region: default
#    registryFetchIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/