server:
  port: 8761

spring.cloud.config.discovery.enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

#eureka:
#  instance:
#    hostname: eureka-service
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://eureka-service:${server.port}/eureka/